#
# test-builds.yml
# Do test builds to catch compile errors
#

name: CI

on:
  push:
    branches:
    - bugfix-2.0.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  test_builds:
    name: Run All Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:
        # Base Environments

        - mega2560

    steps:

    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update
    - name: Check out the PR
      uses: actions/checkout@v2

    - name: Run ${{ matrix.test-platform }} Tests
      run: |
        make tests-single-ci TEST_TARGET=${{ matrix.test-platform }}
